### ISSUE TITLE
Uncaught ReferenceError: DevExpress is not defined

### ISSUE THREAD

**Issue by ihanesman** [DevExpress-Examples/ASPNET-Core-Dashboard-Authentication#1]
Running the project as it is return "Uncaught ReferenceError: DevExpress is not defined" on the console when entering at https://localhost:44317/Home/Dashboard

**Comment by AlexanderKovalenko** [comment]
Hi,

You likely did not restore the **node_modules** folder. Please run the **npm install** command or click the **Restore Packages** menu item in Visual Studio:

![image](https://user-images.githubusercontent.com/24404801/116528694-ce2d0980-a8e4-11eb-9464-cf8e8c07c09b.png)

Let us know if this helps.

**Comment by AlexanderKovalenko** [comment]
Hi,

If you have additional questions regarding our components, please use our Support Center to submit questions:
[https://supportcenter.devexpress.com/ticket/create](https://supportcenter.devexpress.com/ticket/create)
This is our primary support channel.
